baseURL = "https://cmpz.gitlab.io/ie21cp20201"
languageCode = "pt-br"
title = "Lâmpada Solar"
theme = "learn"


pluralizeListTitles = false

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "yellow"
